### ISSUE TITLE
nix build error: Undefined variable g:zkdir

### ISSUE THREAD

**Issue by i077** [ihsanturk/neuron.vim#22]
When nix builds neovim with the neuron.vim plugin, at the same stage as #9 (where it generates `rplugin.vim`), I get an error saying that `g:zkdir` is undefined, even though I have it defined in my neovim config (and I'm pretty sure a default value is given anyways?). Here are the relevant lines:

```
builder for '/nix/store/9xfz8vbwf18qw6sk43ljzqbl28k27r2b-neovim-0.4.3.drv' failed with exit code 1; last 8 log lines:
  Generating remote plugin manifest
  [coc.nvim] creating data directory: /build/tmp.E5DwoN5MCm/.config/coc
  Error detected while processing /nix/store/hgpzpwvwwgkrdgc6cy1yg6r800vj8fh8-vimplugin-neuron.vim-7fab5f7/share/vim-plugins/neuron.vim/plugin/neuron.vim:
  line   47:
  E121: Undefined variable: g:zkdir
  remote/host: python3 host registered plugins ['denite']
  remote/host: generated rplugin manifest: /nix/store/0ll9pgvmbs99yspifyzp204qakd6zipf-neovim-0.4.3/rplugin.vim
  Generating rplugin.vim failed!
```

**Comment by ihsanturk** [comment]
How can I get the same error? I'm using home-manager, can I install the same way that you are following using home-manager?

**Comment by i077** [comment]
I'm also using home-manager. [This](https://github.com/i077/system/blob/02808628f918334db053e010981225de3a32ff38/modules/apps/neovim/default.nix#L53) is where I add neuron-vim to neovim's plugin set (before I commented it out temporarily), and [here](https://github.com/i077/system/blob/02808628f918334db053e010981225de3a32ff38/packages/default.nix#L16) is where that plugin's derivation is defined (since it's not in nixpkgs yet, I still have to update that PR from earlier).

**Comment by ihsanturk** [comment]
I've did not try your installation method <sub>(it looked like rocket science)</sub> but I think it is related to the fact that ftdetect folder is not sourced when nix building the plugin. And the plugin tries to add an autocommand that uses zkdir variable in **plugin/neuron.vim**. So it can't find because ftdetect/neuron.vim not sourced yet (g:zkdir is only defined there). Actually I supposed to add that auto command in **ftdetect/neuron.vim**, not **plugin/neuron.vim**.

Anyways that was the boring description of why that issue happens, the following commit should fix the problem, I hope.

**Comment by ihsanturk** [comment]
Can you specify the dev branch to test this or should I merge that into master?

**Comment by i077** [comment]
> I've did not try your installation method (it looked like rocket science)

lol, I guess once you go far enough down the nix rabbit hole things can look confusing.

> 
> 
> Can you specify the dev branch to test this or should I merge that into master?

I'll use the dev branch and let you know how it goes.

**Comment by i077** [comment]
That worked! Neovim builds and the plugin runs just fine now.

**Comment by i077** [comment]
That worked! Plugin works normally now.
