### ISSUE TITLE
Nix build breaks due to build dependency on neuron/ jq

### ISSUE THREAD

**Issue by srid** [ihsanturk/neuron.vim#9]
My Nix config is here: https://github.com/srid/nix-config/blob/master/nix/nvim/default.nix

Nix tries to build the neuron.vim plugin and fails due to missing neuron and jq:

![image](https://user-images.githubusercontent.com/3998/85228683-df4ae700-b3b2-11ea-86e8-d39d790658a2.png)

I don't know anything about the Vim packaging model, but why should _building_ the plugin need these (what look to be) _runtime_ dependencies?

**Comment by ihsanturk** [comment]
Is it related to nix? I think it is. When I install neuron.vim using [vim-plug](https://github.com/junegunn/vim-plug) I had no issues **even if I have jq and neuron installed via nix & home-manager**.

**Comment by srid** [comment]
This happens with Nix, yes. The nix setup used to work, before 'dev' changes got merged to master. 

Details on how Vim plugins are configured in nixpkgs can be found here: https://nixos.wiki/wiki/Vim ... perhaps @i077 will have some ideas, in the context of https://github.com/NixOS/nixpkgs/pull/90427

**Comment by i077** [comment]
See https://www.github.com/NixOS/nixpkgs/tree/master/pkgs%2Fapplications%2Feditors%2Fneovim%2Fwrapper.nix#L113.

When building the wrapped neovim derivation, nix runs the wrapper to generate a remote plugin manifest (note the "Generating rplugin.vim failed!"). I'm guessing when neovim launches, neuron.vim attempts to run its refresh function, which is where it fails. I think it might be because neuron and jq aren't in the builder's PATH (which makes sense, it's isolated from the user environment).

Might need to specify neuron and jq as `buildInput`s? I'll test that out when I get to my laptop in a few hours.

**Comment by i077** [comment]
Alternatively if there were a way to not run refresh if neovim were just generating rplugin.vim, that would also solve the issue.

**Comment by jonringer** [comment]
you will most likely need to add these dependencies to the related nix package. There should be some examples in overrides.nix which show patching in commands such as `jq` and others.

**Comment by i077** [comment]
Hmm, adding them as build inputs didn't work. This is what I have in a nixpkgs overlay:

```nix
self: super: {
  vimPlugins = super.vimPlugins // {
    neuron-vim = self.vimUtils.buildVimPluginFrom2Nix {
      pname = "neuron.vim";
      version = inputs.neuron-vim.rev;
      src = inputs.neuron-vim;
      buildInputs = with self; [ neuron jq ];
    };
  };
}
```

**Comment by Nadrieril** [comment]
I think that's because the doesn't occur when buildin the derivation for the plugin, but rather when building the neovim derivation

**Comment by Nadrieril** [comment]
A simple solution would be to test for the presence of `neuron` and `jq` in `neuron#refresh_cache()`, and not do anything when they are not in PATH. I would generally like that anyways because I don't always have `neuron` in PATH when I edit zettels, and I would prefer the plugin to not crash in that case.
Another solution would be a nix derivation that patches `neuron#refresh_cache()` and `s:run` to use nix-provided binaries for `neuron` and `jq`.

**Comment by Nadrieril** [comment]
So, I wrote that derivation (be careful, ihsantusk uses tabs so copy-paste might break the patch):
```nix
    "neuron.vim" = pkgs.vimUtils.buildVimPluginFrom2Nix {
      name = "neuron.vim";
      src = extraPluginSrcs."neuron.vim";
      patches = [(pkgs.writeTextFile {
        name = "neuron.vim.patch";
        text = ''
          diff --git a/autoload/neuron.vim b/autoload/neuron.vim
          index cb53a34..e02182b 100644
          --- a/autoload/neuron.vim
          +++ b/autoload/neuron.vim
          @@ -62,7 +62,7 @@ endf
           " TODO: Remove jq dependency find vimscript native solution.
           func! neuron#refresh_cache()
           	let g:cache_zettels = json_decode(s:run(
          -		\ "query --uri 'z:zettels'|jq 'reduce .result[] as $i ({}; .[$i.id]=$i)'"
          +		\ "query --uri 'z:zettels'|${pkgs.jq}/bin/jq 'reduce .result[] as $i ({}; .[$i.id]=$i)'"
           		\ ))
           endf
           
          @@ -72,7 +72,7 @@ func! neuron#edit_zettel(zettel_id)
           endf
           
           func! s:run(cmd)
          -	return system('neuron '.a:cmd)
          +	return system('${pkgs.neuron}/bin/neuron '.a:cmd)
           endf
           
           func! s:expand_zettel_id(zettel_id)
        '';
      })];
    };
```

But of course that didn't solve the problem, because the plugin then tries to look for a zettelkasten directory, and fails x)
```log
building '/nix/store/5wf8xrk2lbfksl728jbm2y8a3bkz7mdx-neovim-0.4.3.drv'...
Generating remote plugin manifest
Error detected while processing function neuron#refresh_cache:
line    1:
E474: Expected null: neuron: user error (Zettelkasten directory /build/tmp.Vs1kdDdGlw/zettelkasten does not exist.)^@
E474: Failed to parse neuron: user error (Zettelkasten directory /build/tmp.Vs1kdDdGlw/zettelkasten does not exist.)^@easytags.vim 3.11: Plug-in not loaded because Exuberant Ctags isn't installed! Please download & install Exuberant Ctags from http://ctags.sf.net
vim-gitgutter: cannot find git. Please set g:gitgutter_git_executable.
remote/host: python3 host registered plugins ['deoplete']
remote/host: generated rplugin manifest: /nix/store/ccf08ml67q7m9pk2awxyah69jaxvl6dv-neovim-0.4.3/rplugin.vim
Generating rplugin.vim failed!
builder for '/nix/store/5wf8xrk2lbfksl728jbm2y8a3bkz7mdx-neovim-0.4.3.drv' failed with exit code 1
```

The problematic line is this: https://github.com/ihsanturk/neuron.vim/blob/b049eec1757775ae8d66ac97bd50318a92c35938/plugin/neuron.vim#L14 . That's a terrible idea in general: I don't want a call to `neuron` everytime I load vim! I think that line should be removed and instead the cache should only be refreshed (and ideally in the background) when I first open a zettel file from my zettelkasten directory.

**Comment by ihsanturk** [comment]
Thank you for kind responses. Looks like there are couple of problems.

### 1. Error Handling 

**Plugin should do nothing when jq and neuron (dependencies) are not in $PATH or print an error message.**

**Possible solution 1:** Take the path of the binaries as a config variable. Something like
```vim
" User has to edit this.
let path_jq = '/path/to/jq'
let path_neuron = '/path/to/jq'
```

**Possible solution 2:** Find out automatically where the jq and neuron with Vim's system function.
```vim
" User doesn't need to edit this.
let path_jq = system('which jq')
let path_neuron = system('which neuron')
``` 
commands. But in this case, the 'sh' setting should be set correctly in vimrc to the get correct paths.

### 2. **Cache problem** as @Nadrieril said
> ...cache should only be refreshed (and ideally in the background) when I first open a zettel file from my zettelkasten directory.

You are actually correct @Nadrieril. There are situations that require to refresh the cache but definitely not every time Vim opens (sorry for odd design). Situations that cache should be refreshed can be listed as:

- First time trying to {open,insert} a zettel from zettelkasten directory.
- Whenever a zettel buffer updated.

Are these correct/enough?

**Comment by srid** [comment]
Refreshing the cache only when needed (in 2) sounds like the right approach to me. You don't want to depend on, much less execute, `neuron` during the time the plugin is being installed (such as in nix) or when vim is launching.

**Comment by ihsanturk** [comment]
Would you check whether e185893fab6a7b98dc0d0cfdf987ee773b35176e works?

**Comment by srid** [comment]
@ihsanturk Confirmed; that fixes it.
